version: '3.8'

services:
  web:
    build: .
    ports:
      - "7070:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
    volumes:
      - ./init:/docker-entrypoint-initdb.d # Schema a ser carregado
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
